use anyhow::{anyhow, Context, Result};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use sqlx::SqlitePool;

use crate::evaluator::StrategyReport;

/// A candidate prompt revision generated by the distiller.
#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct PromptCandidate {
    pub id: String,
    pub agent_id: String,
    pub original_prompt: String,
    pub revised_prompt: String,
    pub rationale: String,
    pub source_report_score: f64,
    pub status: String,
    pub created_at: String,
}

/// Rule-based distillation (default) or LLM-assisted rewrite.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub enum DistillationMode {
    #[default]
    RuleBased,
    LlmAssisted(LlmDistillerConfig),
}

/// Provider configuration for [`DistillationMode::LlmAssisted`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LlmDistillerConfig {
    pub provider: String,
    pub model: String,
    pub prompt_template: String,
}

impl LlmDistillerConfig {
    pub fn default_prompt_template() -> &'static str {
        "You are a prompt engineer. Given the agent's current system prompt and a strategy evaluation report (JSON), reply with the improved full system prompt only — no preamble or markdown fences.\n\nCurrent prompt:\n{current_prompt}\n\nStrategy report (JSON):\n{strategy_report}\n"
    }
}

impl Default for LlmDistillerConfig {
    fn default() -> Self {
        Self {
            provider: "openai".to_string(),
            model: "gpt-4o-mini".to_string(),
            prompt_template: Self::default_prompt_template().to_string(),
        }
    }
}

/// Async hook supplied by the host to run an LLM when using [`DistillationMode::LlmAssisted`].
#[async_trait]
pub trait DistillationCallback: Send + Sync {
    async fn complete(&self, prompt: &str) -> Result<String>;
}

const FORBIDDEN_PATTERNS: &[&str] = &[
    "ignore previous instructions",
    "ignore all previous",
    "disregard your instructions",
    "you are now",
    "new role:",
    "system:",
    "```tool_code",
    "TOOL_CALL",
    "<tool_call>",
    "<function_call>",
];

const MAX_REVISED_PROMPT_LEN: usize = 32_768;

fn validate_change_scope(revised: &str, original: &str) -> Result<()> {
    if revised.len() > MAX_REVISED_PROMPT_LEN {
        tracing::warn!(
            revised_len = revised.len(),
            max = MAX_REVISED_PROMPT_LEN,
            "evolution: rejected candidate — prompt too long"
        );
        anyhow::bail!(
            "revised prompt exceeds maximum length ({} > {MAX_REVISED_PROMPT_LEN})",
            revised.len()
        );
    }

    let revised_lower = revised.to_lowercase();
    for pattern in FORBIDDEN_PATTERNS {
        if revised_lower.contains(pattern) {
            tracing::warn!(
                pattern = %pattern,
                "evolution: rejected candidate — forbidden injection pattern detected"
            );
            anyhow::bail!("revised prompt contains forbidden pattern: '{pattern}'");
        }
    }

    if !original.is_empty() && original.len() > 50 {
        let similarity = strsim_ratio(original, revised);
        if similarity < 0.15 {
            tracing::warn!(
                similarity = format!("{similarity:.2}"),
                original_len = original.len(),
                revised_len = revised.len(),
                "evolution: rejected candidate — excessive divergence from original"
            );
            anyhow::bail!(
                "revised prompt diverges too much from original (similarity {similarity:.2} < 0.15); \
                 this suggests a prompt injection rather than a refinement"
            );
        }
    }

    Ok(())
}

fn strsim_ratio(a: &str, b: &str) -> f64 {
    if a.is_empty() && b.is_empty() {
        return 1.0;
    }
    let max_len = a.len().max(b.len()) as f64;
    if max_len == 0.0 {
        return 1.0;
    }
    let distance = levenshtein_bounded(a, b, (max_len * 0.75) as usize);
    1.0 - (distance as f64 / max_len)
}

fn levenshtein_bounded(a: &str, b: &str, bound: usize) -> usize {
    let a_chars: Vec<char> = a.chars().collect();
    let b_chars: Vec<char> = b.chars().collect();
    let n = a_chars.len();
    let m = b_chars.len();
    if n.abs_diff(m) > bound {
        return bound + 1;
    }
    let mut prev = vec![0usize; m + 1];
    let mut curr = vec![0usize; m + 1];
    for (j, item) in prev.iter_mut().enumerate().take(m + 1) {
        *item = j;
    }
    for i in 1..=n {
        curr[0] = i;
        let mut row_min = curr[0];
        for j in 1..=m {
            let cost = if a_chars[i - 1] == b_chars[j - 1] {
                0
            } else {
                1
            };
            curr[j] = (prev[j] + 1).min(curr[j - 1] + 1).min(prev[j - 1] + cost);
            row_min = row_min.min(curr[j]);
        }
        if row_min > bound {
            return bound + 1;
        }
        std::mem::swap(&mut prev, &mut curr);
    }
    prev[m]
}

/// Generates optimized prompt candidates based on strategy evaluation.
///
/// The distiller analyzes the evaluation report and produces concrete
/// prompt revisions. In a full implementation, this would invoke the
/// LLM itself to rewrite the prompt; here we provide the infrastructure
/// for prompt management and a rule-based heuristic generator.
pub struct PromptDistiller {
    pool: SqlitePool,
}

impl PromptDistiller {
    pub async fn open(pool: SqlitePool) -> Result<Self> {
        sqlx::query(
            r#"
            CREATE TABLE IF NOT EXISTS prompt_candidates (
                id                   TEXT PRIMARY KEY,
                agent_id             TEXT NOT NULL,
                original_prompt      TEXT NOT NULL,
                revised_prompt       TEXT NOT NULL,
                rationale            TEXT NOT NULL,
                source_report_score  REAL NOT NULL DEFAULT 0.0,
                status               TEXT NOT NULL DEFAULT 'pending',
                created_at           TEXT NOT NULL DEFAULT (datetime('now'))
            );
            CREATE INDEX IF NOT EXISTS idx_pc_agent  ON prompt_candidates(agent_id);
            CREATE INDEX IF NOT EXISTS idx_pc_status ON prompt_candidates(status);
            "#,
        )
        .execute(&pool)
        .await?;

        Ok(Self { pool })
    }

    /// Generate a prompt candidate from a strategy report (rule-based; backward compatible).
    pub async fn distill(
        &self,
        agent_id: &str,
        current_prompt: &str,
        report: &StrategyReport,
    ) -> Result<PromptCandidate> {
        self.distill_with_mode(
            agent_id,
            current_prompt,
            report,
            DistillationMode::RuleBased,
            None,
        )
        .await
    }

    /// Generate a prompt candidate using the chosen distillation mode.
    pub async fn distill_with_mode(
        &self,
        agent_id: &str,
        current_prompt: &str,
        report: &StrategyReport,
        mode: DistillationMode,
        llm: Option<&(dyn DistillationCallback + Send + Sync)>,
    ) -> Result<PromptCandidate> {
        let (revised_prompt, rationale) = match mode {
            DistillationMode::RuleBased => Self::rule_based_revision(current_prompt, report),
            DistillationMode::LlmAssisted(cfg) => {
                let cb = llm.ok_or_else(|| {
                    anyhow!("LlmAssisted distillation requires a DistillationCallback")
                })?;
                let report_json =
                    serde_json::to_string_pretty(report).context("serialize strategy report")?;
                let prompt = cfg
                    .prompt_template
                    .replace("{provider}", &cfg.provider)
                    .replace("{model}", &cfg.model)
                    .replacen("{strategy_report}", &report_json, 1)
                    .replacen("{current_prompt}", current_prompt, 1);
                let revised = cb.complete(&prompt).await?;
                let rationale = format!(
                    "LLM-assisted distillation via {}/{}",
                    cfg.provider, cfg.model
                );
                (revised.trim().to_string(), rationale)
            }
        };

        validate_change_scope(&revised_prompt, current_prompt)?;

        let candidate = PromptCandidate {
            id: uuid::Uuid::new_v4().to_string(),
            agent_id: agent_id.to_string(),
            original_prompt: current_prompt.to_string(),
            revised_prompt,
            rationale,
            source_report_score: report.satisfaction_score,
            status: "pending".to_string(),
            created_at: chrono::Utc::now().to_rfc3339(),
        };

        sqlx::query(
            "INSERT INTO prompt_candidates (id, agent_id, original_prompt, revised_prompt, rationale, source_report_score, status, created_at) VALUES (?,?,?,?,?,?,?,?)",
        )
        .bind(&candidate.id)
        .bind(&candidate.agent_id)
        .bind(&candidate.original_prompt)
        .bind(&candidate.revised_prompt)
        .bind(&candidate.rationale)
        .bind(candidate.source_report_score)
        .bind(&candidate.status)
        .bind(&candidate.created_at)
        .execute(&self.pool)
        .await?;

        Ok(candidate)
    }

    fn rule_based_revision(current_prompt: &str, report: &StrategyReport) -> (String, String) {
        let mut revisions = Vec::new();
        let mut rationale_parts = Vec::new();

        if report.satisfaction_score < 0.6 {
            revisions.push("Be more concise and precise in your responses.");
            rationale_parts.push(format!(
                "Low satisfaction score ({:.2})",
                report.satisfaction_score
            ));
        }

        if let Some(tsr) = report.tool_success_rate {
            if tsr < 0.8 {
                revisions
                    .push("Before calling a tool, validate all required parameters carefully.");
                rationale_parts.push(format!("Tool success rate is {:.0}%", tsr * 100.0));
            }
        }

        if report.retry_rate > 0.1 {
            revisions.push(
                "If the user's request is ambiguous, ask a clarifying question before acting.",
            );
            rationale_parts.push(format!("Retry rate is {:.0}%", report.retry_rate * 100.0));
        }

        for rec in &report.recommendations {
            if rec.contains("negative feedback") {
                revisions.push("Pay extra attention to user corrections and adapt your style.");
                rationale_parts.push("High negative feedback ratio".into());
            }
        }

        if revisions.is_empty() {
            revisions.push("Continue with the current approach — performance is satisfactory.");
            rationale_parts.push("No significant issues detected".into());
        }

        let addendum = revisions.join("\n");
        let base_prompt = if let Some(idx) = current_prompt.find("\n\n[Auto-tuned guidelines]") {
            &current_prompt[..idx]
        } else {
            current_prompt
        };
        let revised = format!("{base_prompt}\n\n[Auto-tuned guidelines]\n{addendum}");
        let rationale = rationale_parts.join("; ");
        (revised, rationale)
    }

    /// List pending candidates for an agent.
    pub async fn pending(&self, agent_id: &str) -> Result<Vec<PromptCandidate>> {
        let rows = sqlx::query_as::<_, PromptCandidate>(
            "SELECT * FROM prompt_candidates WHERE agent_id = ? AND status = 'pending' ORDER BY created_at DESC",
        )
        .bind(agent_id)
        .fetch_all(&self.pool)
        .await?;
        Ok(rows)
    }

    /// Accept a candidate (mark as applied).
    pub async fn accept(&self, candidate_id: &str) -> Result<bool> {
        let r = sqlx::query(
            "UPDATE prompt_candidates SET status = 'applied' WHERE id = ? AND status = 'pending'",
        )
        .bind(candidate_id)
        .execute(&self.pool)
        .await?;
        Ok(r.rows_affected() > 0)
    }

    /// Reject a candidate.
    pub async fn reject(&self, candidate_id: &str) -> Result<bool> {
        let r = sqlx::query(
            "UPDATE prompt_candidates SET status = 'rejected' WHERE id = ? AND status = 'pending'",
        )
        .bind(candidate_id)
        .execute(&self.pool)
        .await?;
        Ok(r.rows_affected() > 0)
    }

    /// List all candidates for an agent (any status).
    pub async fn list(&self, agent_id: &str, limit: i64) -> Result<Vec<PromptCandidate>> {
        let rows = sqlx::query_as::<_, PromptCandidate>(
            "SELECT * FROM prompt_candidates WHERE agent_id = ? ORDER BY created_at DESC LIMIT ?",
        )
        .bind(agent_id)
        .bind(limit)
        .fetch_all(&self.pool)
        .await?;
        Ok(rows)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::evaluator::StrategyReport;

    async fn distiller() -> PromptDistiller {
        let pool = SqlitePool::connect("sqlite::memory:").await.unwrap();
        PromptDistiller::open(pool).await.unwrap()
    }

    fn mock_report(score: f64, tool_sr: Option<f64>, retry: f64) -> StrategyReport {
        StrategyReport {
            agent_id: "main".into(),
            total_interactions: 100,
            sample_size: 100,
            thumbs_up: 70,
            thumbs_down: 30,
            avg_rating: Some(3.5),
            tool_success_rate: tool_sr,
            retry_rate: retry,
            satisfaction_score: score,
            recommendations: vec![],
        }
    }

    #[tokio::test]
    async fn distill_low_satisfaction() {
        let d = distiller().await;
        let report = mock_report(0.3, Some(0.6), 0.2);
        let c = d
            .distill("main", "You are helpful.", &report)
            .await
            .unwrap();

        assert!(c.revised_prompt.contains("[Auto-tuned guidelines]"));
        assert!(c.revised_prompt.contains("concise"));
        assert!(c.rationale.contains("satisfaction"));
    }

    #[tokio::test]
    async fn accept_reject_workflow() {
        let d = distiller().await;
        let report = mock_report(0.8, Some(0.95), 0.02);
        let c = d
            .distill("main", "You are helpful.", &report)
            .await
            .unwrap();

        let pending = d.pending("main").await.unwrap();
        assert_eq!(pending.len(), 1);

        d.accept(&c.id).await.unwrap();
        let pending = d.pending("main").await.unwrap();
        assert_eq!(pending.len(), 0);
    }

    #[tokio::test]
    async fn good_performance_no_major_changes() {
        let d = distiller().await;
        let report = mock_report(0.9, Some(0.99), 0.01);
        let c = d
            .distill("main", "You are helpful.", &report)
            .await
            .unwrap();

        assert!(c.revised_prompt.contains("satisfactory"));
    }

    struct MockLlm {
        out: String,
    }

    #[async_trait]
    impl DistillationCallback for MockLlm {
        async fn complete(&self, _prompt: &str) -> Result<String> {
            Ok(self.out.clone())
        }
    }

    #[tokio::test]
    async fn llm_assisted_uses_callback_output() {
        let d = distiller().await;
        let report = mock_report(0.5, Some(0.9), 0.05);
        let cfg = LlmDistillerConfig {
            provider: "test".into(),
            model: "mock".into(),
            prompt_template: "PROMPT\n{current_prompt}\n---\n{strategy_report}".into(),
        };
        let mock = MockLlm {
            out: "REVISED_SYSTEM_PROMPT".into(),
        };
        let c = d
            .distill_with_mode(
                "main",
                "You are helpful.",
                &report,
                DistillationMode::LlmAssisted(cfg),
                Some(&mock as &(dyn DistillationCallback + Send + Sync)),
            )
            .await
            .unwrap();

        assert_eq!(c.revised_prompt, "REVISED_SYSTEM_PROMPT");
        assert!(c.rationale.contains("test/mock"));
    }

    #[tokio::test]
    async fn llm_assisted_without_callback_errors() {
        let d = distiller().await;
        let report = mock_report(0.5, None, 0.0);
        let err = d
            .distill_with_mode(
                "main",
                "x",
                &report,
                DistillationMode::LlmAssisted(LlmDistillerConfig::default()),
                None,
            )
            .await
            .unwrap_err();
        assert!(err.to_string().contains("DistillationCallback"));
    }
}
