/**
 * Lucide → Phosphor icon name mapping.
 * This file is a reference for migration and will be removed after migration is complete.
 *
 * Phosphor naming conventions:
 * - PascalCase components (same as Lucide)
 * - Some names differ significantly
 */

export const LUCIDE_TO_PHOSPHOR = {
  AlertCircle: "WarningCircle",
  AlertTriangle: "Warning",
  Archive: "Archive",
  ArrowDown: "ArrowDown",
  ArrowRight: "ArrowRight",
  ArrowUp: "ArrowUp",
  Bell: "Bell",
  BookOpen: "BookOpen",
  Bot: "Robot",
  Box: "Cube",
  Brain: "Brain",
  Calendar: "Calendar",
  CalendarClock: "CalendarBlank", // Phosphor has CalendarBlank, use with Clock nearby
  CalendarDays: "Calendar",
  Check: "Check",
  CheckCheck: "Checks",
  CheckCircle: "CheckCircle",
  CheckCircle2: "CheckCircle",
  ChevronDown: "CaretDown",
  ChevronLeft: "CaretLeft",
  ChevronRight: "CaretRight",
  ChevronUp: "CaretUp",
  Circle: "Circle",
  CircleDot: "CircleDashed", // or RadioButton
  ClipboardPaste: "ClipboardText",
  Clock: "Clock",
  Code2: "Code",
  Compass: "Compass",
  Copy: "Copy",
  Database: "Database",
  DollarSign: "CurrencyDollar",
  Download: "DownloadSimple",
  ExternalLink: "ArrowSquareOut",
  Eye: "Eye",
  EyeOff: "EyeSlash",
  File: "File",
  FileSearch: "FileSearch",
  FileText: "FileText",
  Folder: "Folder",
  FolderOpen: "FolderOpen",
  FolderPlus: "FolderPlus",
  GitBranch: "GitBranch",
  Globe: "Globe",
  History: "ClockCounterClockwise",
  Image: "Image",
  Info: "Info",
  KeyRound: "Key",
  Layout: "Layout",
  Layers: "Stack",
  Lightbulb: "Lightbulb",
  Link: "Link",
  ListTodo: "ListChecks",
  Loader2: "SpinnerGap",
  Lock: "Lock",
  LucideProvider: null, // Replaced by IconContext.Provider
  Maximize2: "ArrowsOut",
  MessageCircle: "ChatCircle",
  MessageSquare: "ChatSquare", // or ChatText
  Minus: "Minus",
  Monitor: "Monitor",
  Moon: "Moon",
  MoreHorizontal: "DotsThree",
  PackagePlus: "PackagePlus", // Phosphor doesn't have exact — use Package
  PackageSearch: "Package",
  Palette: "Palette",
  PanelBottom: "SidebarSimple", // rotated conceptually
  PanelLeft: "SidebarSimple",
  PanelLeftClose: "SidebarSimple",
  PanelRightClose: "SidebarSimple",
  Paperclip: "Paperclip",
  Pause: "Pause",
  Pencil: "PencilSimple",
  PenLine: "PenNib",
  PenTool: "PenNib",
  Pin: "PushPin",
  PinOff: "PushPinSlash",
  Play: "Play",
  Plug: "Plug",
  PlugZap: "PlugsConnected",
  Plus: "Plus",
  Puzzle: "PuzzlePiece",
  QrCode: "QrCode",
  RefreshCw: "ArrowsClockwise",
  RotateCcw: "ArrowCounterClockwise",
  RotateCw: "ArrowClockwise",
  Save: "FloppyDisk",
  Scissors: "Scissors",
  Search: "MagnifyingGlass",
  Server: "HardDrives",
  Settings: "Gear",
  Settings2: "GearSix",
  Shield: "Shield",
  ShieldAlert: "ShieldWarning",
  ShieldCheck: "ShieldCheck",
  ShieldOff: "ShieldSlash",
  ShieldX: "ShieldSlash",
  Smartphone: "DeviceMobile",
  Sparkles: "Sparkle",
  Square: "Square",
  Sun: "Sun",
  TableProperties: "Table",
  Target: "Crosshair",
  Terminal: "Terminal",
  TerminalSquare: "TerminalWindow",
  TextSelect: "TextAa",
  ThumbsDown: "ThumbsDown",
  ThumbsUp: "ThumbsUp",
  Timer: "Timer",
  ToggleLeft: "ToggleLeft",
  ToggleRight: "ToggleRight",
  Trash2: "Trash",
  Unlink: "LinkBreak",
  Upload: "UploadSimple",
  User: "User",
  Volume2: "SpeakerHigh",
  Wifi: "Wifi",
  WifiOff: "WifiSlash",
  Wrench: "Wrench",
  X: "X",
  XCircle: "XCircle",
  Zap: "Lightning",
  ZoomIn: "MagnifyingGlassPlus",
  ZoomOut: "MagnifyingGlassMinus",
} as const;
